#include <catch2/catch_all.hpp>

#include <string>

#include "cli.h"

namespace
{

using resonate::test::ToolRun;

/* The declarations the emission cases share: an enum, a bitmask with an
   explicit bit, an inlined struct, a component using all of them, and a node
   type (metadata only). */
const char* const kModule = "resonate.test";

const char* const kSchema = R"xml(<schema module="resonate.test">
  <enum name="Flags" width="u8">
    <value name="Idle"/>
    <value name="Busy"/>
  </enum>

  <bitmask name="Mask" width="u32">
    <flag name="Fire"/>
    <flag name="Ice" bit="3"/>
  </bitmask>

  <struct name="Inner">
    <field name="a" type="i32"/>
    <field name="b" type="i32"/>
  </struct>

  <component name="Health" version="1">
    <field name="current" type="i32" min="0" default="100"/>
    <field name="flags" type="Flags" default="Busy"/>
    <field name="mask" type="Mask" default="Ice"/>
    <field name="inner" type="Inner"/>
    <field name="owner" type="entity"/>
    <field name="slots" type="blob"/>
    <field name="position" type="vec3" default="1 2 3"/>
    <field name="rotation" type="quat" default="0 0 0 1"/>
    <field name="matrix" type="mat4"/>
  </component>

  <node name="Record" version="1">
    <field name="health" type="Health"/>
  </node>
</schema>
)xml";

struct EmitCase
{
    std::string root;
    std::string gen;

    explicit EmitCase(const std::string& name)
        : root(resonate::test::scratchDirectory(name)), gen(root + "/gen")
    {
        resonate::test::writeTextFile(root + "/case.rschema", kSchema);
    }

    ToolRun compile() const
    {
        return resonate::test::runSchemac("--root \"" + root + "\" --out \"" + gen + "\"");
    }

    std::string header() const
    {
        return resonate::test::readTextFile(gen + "/resonate.test/components.gen.h");
    }

    std::string metadata() const
    {
        return resonate::test::readTextFile(gen + "/resonate.test.schema.json");
    }
};

void requireContains(const std::string& text, const std::string& fragment)
{
    INFO(fragment);
    REQUIRE(text.find(fragment) != std::string::npos);
}

} // namespace

TEST_CASE("the generated header carries the types, traits, versions and frozen layout",
          "[schema][emit]")
{
    const EmitCase testCase("emit-header");
    const ToolRun run = testCase.compile();
    INFO(run.output);
    REQUIRE(run.exitCode == 0);
    REQUIRE(run.output.find("1 module(s), 5 type(s) from 1 schema file(s), 2 written") !=
            std::string::npos);

    const std::string header = testCase.header();
    REQUIRE_FALSE(header.empty());
    requireContains(header, "Generated by schemac ");
    requireContains(header, "namespace resonate::test\n{");
    requireContains(header, "#include <resonate/core/math.h>");
    requireContains(header, "#include <resonate/ecs/blob.h>");
    requireContains(header, "#include <resonate/ecs/component.h>");
    requireContains(header, "#include <resonate/ecs/entity.h>");

    requireContains(header, "enum class Flags : std::uint8_t");
    requireContains(header, "    Busy = 1,\n");
    requireContains(header, "enum class Mask : std::uint32_t");
    requireContains(header, "    Ice = 1U << 3,\n");
    requireContains(header, "[[nodiscard]] constexpr Mask operator|(Mask left, Mask right)");

    requireContains(header, "struct Inner\n{\n    std::int32_t a{};\n    std::int32_t b{};\n};");
    requireContains(header, "inline constexpr std::uint32_t kHealthVersion = 1;");
    requireContains(header, "    std::int32_t current = 100;\n");
    requireContains(header, "    Flags flags = Flags::Busy;\n");
    requireContains(header, "    Mask mask = Mask::Ice;\n");
    requireContains(header, "    Inner inner{};\n");
    requireContains(header, "    resonate::ecs::Entity owner{};\n");
    requireContains(header, "    resonate::ecs::BlobHandle slots{};\n");
    requireContains(header, "    resonate::Vec3 position = resonate::Vec3{1.0F, 2.0F, 3.0F};\n");
    requireContains(header, "    resonate::Quat rotation = resonate::Quat{0.0F, 0.0F, 0.0F, 1.0F};\n");
    requireContains(header, "    resonate::Mat4 matrix{};\n");

    requireContains(header,
                    "RESONATE_COMPONENT(resonate::test::Health, \"resonate.test.Health\");");

    requireContains(header, "static_assert(sizeof(resonate::test::Health) == 128,");
    requireContains(header, "static_assert(alignof(resonate::test::Health) == 4,");
    requireContains(header, "static_assert(offsetof(resonate::test::Health, flags) == 4,");
    requireContains(header, "static_assert(offsetof(resonate::test::Health, mask) == 8,");
    requireContains(header, "static_assert(offsetof(resonate::test::Health, inner) == 12,");
    requireContains(header, "static_assert(offsetof(resonate::test::Health, owner) == 20,");
    requireContains(header, "static_assert(offsetof(resonate::test::Health, slots) == 28,");
    requireContains(header, "static_assert(offsetof(resonate::test::Health, position) == 36,");
    requireContains(header, "static_assert(offsetof(resonate::test::Health, rotation) == 48,");
    requireContains(header, "static_assert(offsetof(resonate::test::Health, matrix) == 64,");
    requireContains(header, "static_assert(sizeof(resonate::ecs::BlobHandle) == 8,");

    /* The document family is metadata only in v0. */
    REQUIRE(header.find("Record") == std::string::npos);

    const std::string metadata = testCase.metadata();
    requireContains(metadata, "\"module\": \"resonate.test\"");
    requireContains(metadata, "\"kind\": \"component\"");
    requireContains(metadata, "\"qualifiedName\": \"resonate.test.Health\"");
    requireContains(metadata, "\"version\": 1");
    requireContains(metadata, "\"kind\": \"node\"");
    requireContains(metadata, "\"qualifiedName\": \"resonate.test.Record\"");
    requireContains(metadata, "\"declaredType\": \"resonate.test.Flags\"");
    requireContains(metadata, "\"default\": \"100\"");
    requireContains(metadata, "\"default\": \"1 2 3\"");
    requireContains(metadata, "\"default\": \"0 0 0 1\"");
    requireContains(metadata, "\"type\": \"blob\"");
    requireContains(metadata, "\"type\": \"vec3\"");
    requireContains(metadata, "\"type\": \"mat4\"");
    requireContains(metadata, "\"bit\": 3");
}

TEST_CASE("a module of document node types generates metadata and a header without types",
          "[schema][emit]")
{
    const std::string root = resonate::test::scratchDirectory("emit-node-only");
    resonate::test::writeTextFile(root + "/case.rschema", R"xml(<schema module="resonate.records">
  <node name="SceneRecord" version="1">
    <field name="label" type="u32"/>
  </node>
</schema>
)xml");

    const ToolRun run =
        resonate::test::runSchemac("--root \"" + root + "\" --out \"" + root + "/gen\"");
    INFO(run.output);
    REQUIRE(run.exitCode == 0);

    const std::string header =
        resonate::test::readTextFile(root + "/gen/resonate.records/components.gen.h");
    requireContains(header, "declares no storage types");
    REQUIRE(header.find("RESONATE_COMPONENT") == std::string::npos);
    /* Nothing to register and nothing to lay out, so nothing to include. */
    REQUIRE(header.find("#include <resonate/ecs/component.h>") == std::string::npos);

    const std::string metadata =
        resonate::test::readTextFile(root + "/gen/resonate.records.schema.json");
    requireContains(metadata, "\"kind\": \"node\"");
    requireContains(metadata, "\"version\": 1");
}

TEST_CASE("a run that changes nothing writes nothing", "[schema][emit]")
{
    const EmitCase testCase("emit-idempotent");

    const ToolRun first = testCase.compile();
    INFO(first.output);
    REQUIRE(first.exitCode == 0);
    REQUIRE(first.output.find("2 written") != std::string::npos);

    const std::string header = testCase.header();
    const std::string metadata = testCase.metadata();

    const ToolRun second = testCase.compile();
    INFO(second.output);
    REQUIRE(second.exitCode == 0);
    REQUIRE(second.output.find("0 written") != std::string::npos);

    /* Byte-identical, so nothing downstream sees a changed file. */
    REQUIRE(testCase.header() == header);
    REQUIRE(testCase.metadata() == metadata);
}

TEST_CASE("a schema error leaves the previous output alone", "[schema][emit]")
{
    const EmitCase testCase("emit-error-keeps-output");
    REQUIRE(testCase.compile().exitCode == 0);
    const std::string header = testCase.header();

    resonate::test::writeTextFile(testCase.root + "/case.rschema",
                                  "<schema module=\"resonate.test\"><component name=\"H\" "
                                  "version=\"1\"><field name=\"f\" type=\"Nope\"/></component>"
                                  "</schema>\n");

    const ToolRun failed = testCase.compile();
    INFO(failed.output);
    REQUIRE(failed.exitCode == 1);
    REQUIRE(testCase.header() == header);
}
