using System.Collections.Generic;
using System.Text;
using Resonate.Tools.Schemac.Schema;

namespace Resonate.Tools.Schemac.Emit;

/* The storage family's C++ form: plain structs in the owning module's
   namespace, their ECS traits registration, the version and migration entry
   points, and the frozen layout as static_asserts. The document family
   generates no code in v0 — its declarations live in the metadata. */
internal static class CppEmitter
{
    internal static string Render(ModuleUnit module)
    {
        StringBuilder text = new();
        text.Append("/* Generated by schemac ").Append(Schemac.Version).Append(" from ");
        for (int index = 0; index < module.Files.Count; ++index)
        {
            text.Append(index == 0 ? "" : ", ").Append(PathText.Relative(module.Files[index].Path));
        }
        text.Append("; do not edit. */\n");

        string guard = Guard(module.Id);
        text.Append("#ifndef ").Append(guard).Append('\n');
        text.Append("#define ").Append(guard).Append("\n\n");
        text.Append("#include <cstddef>\n");
        text.Append("#include <cstdint>\n\n");

        List<TypeDecl> storage = [];
        List<TypeDecl> components = [];
        bool needsEntity = false;
        bool needsBlob = false;
        bool needsMath = false;
        foreach (TypeDecl type in module.Types)
        {
            if (!type.IsStorage)
            {
                continue;
            }
            storage.Add(type);
            if (type.Kind == TypeKind.Component)
            {
                components.Add(type);
            }
            foreach (FieldDecl field in type.Fields)
            {
                needsEntity |= field.Primitive?.Kind == PrimitiveKind.Entity;
                needsBlob |= field.Primitive?.Kind == PrimitiveKind.Blob;
                needsMath |= field.Primitive?.Kind == PrimitiveKind.Math;
            }
        }

        if (needsMath)
        {
            text.Append("#include <resonate/core/math.h>\n");
        }
        if (needsBlob)
        {
            text.Append("#include <resonate/ecs/blob.h>\n");
        }
        if (components.Count > 0)
        {
            text.Append("#include <resonate/ecs/component.h>\n");
        }
        if (needsEntity)
        {
            text.Append("#include <resonate/ecs/entity.h>\n");
        }

        if (storage.Count == 0)
        {
            text.Append("\n/* This module declares no storage types; only its metadata is generated. */\n");
            text.Append("\n#endif /* ").Append(guard).Append(" */\n");
            return text.ToString();
        }

        string space = Namespace(module.Id);
        text.Append("\nnamespace ").Append(space).Append("\n{\n");
        foreach (TypeDecl type in storage)
        {
            text.Append('\n');
            switch (type.Kind)
            {
                case TypeKind.Enum:
                    WriteEnum(text, type);
                    break;
                case TypeKind.Bitmask:
                    WriteBitmask(text, type);
                    break;
                default:
                    WriteRecord(text, type);
                    break;
            }
        }
        text.Append("\n} // namespace ").Append(space).Append('\n');

        if (components.Count > 0)
        {
            text.Append("\nnamespace resonate::ecs\n{\n");
            foreach (TypeDecl type in components)
            {
                text.Append("\nRESONATE_COMPONENT(").Append(CppName(type.QualifiedName)).Append(", \"")
                    .Append(type.QualifiedName).Append("\");\n");
            }
            text.Append("\n} // namespace resonate::ecs\n");
        }

        text.Append("\n/* The frozen layout: the metadata and every other language's view are built\n"
                    + "   from these numbers, so a compiler that would lay the declarations out\n"
                    + "   differently has to fail here instead of shifting bytes silently. */\n");
        foreach (TypeDecl type in storage)
        {
            WriteLayoutAssertions(text, type);
        }
        if (needsEntity)
        {
            text.Append("\nstatic_assert(sizeof(resonate::ecs::Entity) == 8,\n"
                        + "              \"the schema's entity fields assume the ECS handle is 8 bytes\");\n");
        }
        if (needsBlob)
        {
            text.Append("\nstatic_assert(sizeof(resonate::ecs::BlobHandle) == 8,\n"
                        + "              \"the schema's blob fields assume the ECS handle is 8 bytes\");\n");
        }

        text.Append("\n#endif /* ").Append(guard).Append(" */\n");
        return text.ToString();
    }

    private static void WriteEnum(StringBuilder text, TypeDecl type)
    {
        Primitive width = Primitives.Find(type.Width)!;
        text.Append("enum class ").Append(type.Name).Append(" : ").Append(width.Cpp).Append("\n{\n");
        foreach (EnumValueDecl value in type.Values)
        {
            text.Append("    ").Append(value.Name).Append(" = ").Append(IntegerLiteral(type, value.Literal))
                .Append(",\n");
        }
        text.Append("};\n");
    }

    private static void WriteBitmask(StringBuilder text, TypeDecl type)
    {
        Primitive width = Primitives.Find(type.Width)!;
        string shift = width.Size == 8 ? "1ULL" : "1U";

        text.Append("enum class ").Append(type.Name).Append(" : ").Append(width.Cpp).Append("\n{\n");
        foreach (BitmaskFlagDecl flag in type.Flags)
        {
            text.Append("    ").Append(flag.Name).Append(" = ").Append(shift).Append(" << ")
                .Append(flag.Bit).Append(",\n");
        }
        text.Append("};\n\n");

        foreach (string op in new[] { "|", "&" })
        {
            text.Append("\n[[nodiscard]] constexpr ").Append(type.Name).Append(" operator").Append(op)
                .Append('(').Append(type.Name).Append(" left, ").Append(type.Name)
                .Append(" right) noexcept\n{\n");
            text.Append("    return static_cast<").Append(type.Name).Append(">(static_cast<")
                .Append(width.Cpp).Append(">(left) ").Append(op).Append(" static_cast<")
                .Append(width.Cpp).Append(">(right));\n}\n");
        }
    }

    private static void WriteRecord(StringBuilder text, TypeDecl type)
    {
        text.Append("struct ").Append(type.Name).Append("\n{\n");
        foreach (FieldDecl field in type.Fields)
        {
            text.Append("    ").Append(FieldType(field)).Append(' ').Append(field.Name)
                .Append(FieldInitialiser(field)).Append(";\n");
        }
        text.Append("};\n");

        if (type.Kind == TypeKind.Component)
        {
            text.Append("\ninline constexpr std::uint32_t k").Append(type.Name)
                .Append("Version = ").Append(type.Version).Append(";\n");

            foreach (MigrationDecl migration in type.Migrations)
            {
                string entry = MigrationEntry(type, migration);
                text.Append("\n/* Version ").Append(migration.From).Append(" -> ").Append(migration.To)
                    .Append(": implemented by the module that owns '").Append(type.Name)
                    .Append("'. Taking the address is what turns a missing definition into a\n"
                            + "   link error wherever the entry is used. */\n");
                text.Append("bool ").Append(entry).Append("(const void* payload, std::size_t size, ")
                    .Append(type.Name).Append("& out);\n");
                text.Append("inline constexpr bool (*k").Append(type.Name)
                    .Append("MigrationFrom").Append(migration.From)
                    .Append(")(const void*, std::size_t, ").Append(type.Name).Append("&) = &")
                    .Append(entry).Append(";\n");
            }
        }
    }

    private static string MigrationEntry(TypeDecl type, MigrationDecl migration)
    {
        return $"migrate{type.Name}From{migration.From}";
    }

    private static void WriteLayoutAssertions(StringBuilder text, TypeDecl type)
    {
        string qualified = CppName(type.QualifiedName);
        if (type.Layout is not Layout layout)
        {
            return;
        }

        text.Append('\n');
        text.Append("static_assert(sizeof(").Append(qualified).Append(") == ").Append(layout.Size)
            .Append(",\n              \"").Append(type.Name).Append(": the frozen size is ")
            .Append(layout.Size).Append("\");\n");
        text.Append("static_assert(alignof(").Append(qualified).Append(") == ").Append(layout.Align)
            .Append(",\n              \"").Append(type.Name).Append(": the frozen alignment is ")
            .Append(layout.Align).Append("\");\n");

        if (type.Kind is TypeKind.Struct or TypeKind.Component)
        {
            foreach (FieldDecl field in type.Fields)
            {
                text.Append("static_assert(offsetof(").Append(qualified).Append(", ").Append(field.Name)
                    .Append(") == ").Append(field.Offset).Append(",\n              \"")
                    .Append(type.Name).Append('.').Append(field.Name)
                    .Append(": the frozen offset is ").Append(field.Offset).Append("\");\n");
            }
        }
    }

    /* Inside the module's own namespace a companion type is named plainly; the
       traits macro's argument is not, since it lands in `resonate::ecs`. */
    private static string FieldType(FieldDecl field)
    {
        if (field.Primitive is Primitive primitive)
        {
            return primitive.Cpp;
        }
        return field.Resolved?.Name ?? field.TypeName;
    }

    private static string FieldInitialiser(FieldDecl field)
    {
        string? value = field.DefaultText;
        if (value is null)
        {
            return "{}";
        }

        if (field.Primitive is Primitive primitive)
        {
            return primitive.Kind switch
            {
                PrimitiveKind.Boolean => $" = {value}",
                PrimitiveKind.Float => $" = {(primitive.Bits == 32 ? FloatLiteral(value, true) : FloatLiteral(value, false))}",
                PrimitiveKind.Integer => $" = {IntegerLiteral(primitive, value)}",
                PrimitiveKind.Math => $" = {MathDefault(primitive, value)}",
                _ => "{}",
            };
        }

        TypeDecl? resolved = field.Resolved;
        if (resolved is null)
        {
            return "{}";
        }

        if (resolved.Kind == TypeKind.Enum)
        {
            return $" = {resolved.Name}::{value}";
        }
        if (resolved.Kind == TypeKind.Bitmask)
        {
            foreach (BitmaskFlagDecl flag in resolved.Flags)
            {
                if (flag.Name == value)
                {
                    return $" = {resolved.Name}::{value}";
                }
            }
            return $" = static_cast<{resolved.Name}>({value}U)";
        }
        return "{}";
    }

    /* A C++ float literal needs a fractional part and the f32 suffix; the
       canonical text may be a plain integer ("1") for a whole value. */
    private static string FloatLiteral(string text, bool single)
    {
        string literal = text.Contains('.') || text.Contains('e') || text.Contains('E')
                             ? text
                             : text + ".0";
        return single ? literal + "F" : literal;
    }

    /* One f32 literal per component, as aggregate initialisation: the canonical
       default text is already one number per component. */
    private static string MathDefault(Primitive primitive, string value)
    {
        string[] parts = value.Split(' ');
        StringBuilder literals = new();
        foreach (string part in parts)
        {
            if (literals.Length > 0)
            {
                literals.Append(", ");
            }
            literals.Append(FloatLiteral(part, true));
        }
        return $"{primitive.Cpp}{{{literals}}}";
    }

    private static string IntegerLiteral(TypeDecl type, string text)
    {
        return IntegerLiteral(Primitives.Find(type.Width)!, text);
    }

    private static string IntegerLiteral(Primitive primitive, string text)
    {
        if (primitive.Bits == 64)
        {
            return text + (primitive.Signed ? "LL" : "ULL");
        }
        return text;
    }

    private static string Namespace(string module)
    {
        return module.Replace(".", "::");
    }

    private static string CppName(string qualified)
    {
        return qualified.Replace(".", "::");
    }

    private static string Guard(string module)
    {
        string name = module.ToUpperInvariant().Replace('.', '_');
        return $"RESONATE_GEN_{name}_COMPONENTS_GEN_H";
    }
}
